import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

const SUPPORT_WHATSAPP = '5591992002607';

serve(async (req) => {
  // Handle CORS preflight
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    // Get the authorization header
    const authHeader = req.headers.get('Authorization');
    if (!authHeader) {
      throw new Error('Missing authorization header');
    }

    // Get user from token
    const { data: { user }, error: userError } = await supabase.auth.getUser(
      authHeader.replace('Bearer ', '')
    );

    if (userError || !user) {
      throw new Error('Unauthorized');
    }

    const { name, company, problem, client_id, attachment_urls = [] } = await req.json();

    if (!name || !company || !problem) {
      throw new Error('Missing required fields: name, company, problem');
    }

    console.log(`Creating support ticket for user ${user.id}`);

    // Insert the ticket (ticket_number will be generated by trigger)
    const { data: ticket, error: insertError } = await supabase
      .from('support_tickets')
      .insert({
        user_id: user.id,
        client_id: client_id || null,
        name,
        company,
        problem,
        attachment_urls,
        whatsapp_sent: true,
      })
      .select()
      .single();

    if (insertError) {
      console.error('Error inserting ticket:', insertError);
      throw new Error('Failed to create ticket');
    }

    console.log(`Ticket created: ${ticket.ticket_number}`);

    // Format the date
    const createdAt = new Date(ticket.created_at);
    const formattedDate = createdAt.toLocaleDateString('pt-BR', {
      day: '2-digit',
      month: '2-digit',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });

    // Create WhatsApp message
    const message = `🎫 *NOVO TICKET DE SUPORTE*
━━━━━━━━━━━━━━━━━━━━━

📌 Ticket: #${ticket.ticket_number}
👤 Nome: ${name}
🏢 Empresa: ${company}
📅 Data: ${formattedDate}

📝 *Problema Relatado:*
${problem}

━━━━━━━━━━━━━━━━━━━━━`;

    // Create WhatsApp URL
    const whatsappUrl = `https://api.whatsapp.com/send?phone=${SUPPORT_WHATSAPP}&text=${encodeURIComponent(message)}`;

    return new Response(
      JSON.stringify({
        success: true,
        ticket: {
          id: ticket.id,
          ticket_number: ticket.ticket_number,
          created_at: ticket.created_at,
        },
        whatsapp_url: whatsappUrl,
      }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 200,
      }
    );
  } catch (error) {
    console.error('Error in send-support-whatsapp:', error);
    const errorMessage = error instanceof Error ? error.message : 'Internal server error';
    return new Response(
      JSON.stringify({ 
        success: false, 
        error: errorMessage
      }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: errorMessage === 'Unauthorized' ? 401 : 400,
      }
    );
  }
});
