-- 1. Criar função RPC exec_sql para uso futuro da edge function
CREATE OR REPLACE FUNCTION public.exec_sql(sql TEXT)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
BEGIN
  EXECUTE sql;
END;
$$;

-- 2. Criar função de acesso para cliente Santa Madre
CREATE OR REPLACE FUNCTION public.has_sm_client_access(_user_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE SECURITY DEFINER
SET search_path TO 'public'
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.tryvia_analytics_profiles p
    JOIN public.tryvia_analytics_clients c ON p.client_id = c.id
    WHERE p.id = _user_id AND c.name = 'Santa Madre'
  )
  OR public.has_analytics_role(_user_id, 'admin')
$$;

-- 3. Criar tabelas Google Ads
CREATE TABLE IF NOT EXISTS public.sm_google_ad_metrics (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id uuid NOT NULL DEFAULT '1e9bc1d6-a6d9-470c-9a90-6afc96ba9ada'::uuid REFERENCES public.tryvia_analytics_clients(id),
  date date NOT NULL,
  source text NOT NULL DEFAULT 'google_ads',
  campaign_name text,
  adset_name text,
  ad_name text,
  impressions integer DEFAULT 0,
  clicks integer DEFAULT 0,
  cost numeric DEFAULT 0,
  conversions integer DEFAULT 0,
  revenue numeric DEFAULT 0,
  leads integer DEFAULT 0,
  reach integer DEFAULT 0,
  results integer DEFAULT 0,
  result_type text,
  status text DEFAULT 'ENABLED',
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.sm_google_keywords (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id uuid NOT NULL DEFAULT '1e9bc1d6-a6d9-470c-9a90-6afc96ba9ada'::uuid REFERENCES public.tryvia_analytics_clients(id),
  date date NOT NULL,
  keyword text NOT NULL,
  campaign_name text,
  match_type text,
  status text DEFAULT 'active',
  impressions integer DEFAULT 0,
  clicks integer DEFAULT 0,
  cost numeric DEFAULT 0,
  conversions integer DEFAULT 0,
  quality_score integer,
  created_at timestamptz DEFAULT now()
);

-- 4. Criar tabelas Meta Ads
CREATE TABLE IF NOT EXISTS public.sm_meta_campaigns (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  account_id text NOT NULL,
  campaign_id text NOT NULL,
  campaign_name text,
  objective text,
  status text,
  effective_status text,
  daily_budget numeric,
  lifetime_budget numeric,
  date_start date NOT NULL,
  date_end date NOT NULL,
  spend numeric DEFAULT 0,
  reach bigint DEFAULT 0,
  impressions bigint DEFAULT 0,
  results integer DEFAULT 0,
  cost_per_result numeric,
  conversions integer DEFAULT 0,
  cost_per_conversion numeric,
  leads integer DEFAULT 0,
  messages integer DEFAULT 0,
  page_views integer DEFAULT 0,
  result_type text,
  created_time timestamptz,
  extracted_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.sm_meta_adsets (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  account_id text NOT NULL,
  campaign_id text NOT NULL,
  adset_id text NOT NULL,
  adset_name text,
  optimization_goal text,
  billing_event text,
  status text,
  effective_status text,
  daily_budget numeric,
  lifetime_budget numeric,
  date_start date NOT NULL,
  date_end date NOT NULL,
  spend numeric DEFAULT 0,
  reach bigint DEFAULT 0,
  impressions bigint DEFAULT 0,
  results integer DEFAULT 0,
  cost_per_result numeric,
  conversions integer DEFAULT 0,
  cost_per_conversion numeric,
  leads integer DEFAULT 0,
  messages integer DEFAULT 0,
  page_views integer DEFAULT 0,
  result_type text,
  created_time timestamptz,
  extracted_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.sm_meta_ads (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  account_id text NOT NULL,
  campaign_id text NOT NULL,
  adset_id text NOT NULL,
  ad_id text NOT NULL,
  ad_name text,
  creative_id text,
  status text,
  effective_status text,
  date_start date NOT NULL,
  date_end date NOT NULL,
  spend numeric DEFAULT 0,
  reach bigint DEFAULT 0,
  impressions bigint DEFAULT 0,
  results integer DEFAULT 0,
  cost_per_result numeric,
  conversions integer DEFAULT 0,
  cost_per_conversion numeric,
  leads integer DEFAULT 0,
  messages integer DEFAULT 0,
  page_views integer DEFAULT 0,
  result_type text,
  image_url text,
  thumbnail_url text,
  video_id text,
  created_time timestamptz,
  extracted_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.sm_meta_campaigns_breakdowns (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  account_id text NOT NULL,
  campaign_id text NOT NULL,
  campaign_name text,
  date_start date NOT NULL,
  date_end date NOT NULL,
  age text DEFAULT '',
  gender text DEFAULT '',
  publisher_platform text DEFAULT '',
  platform_position text DEFAULT '',
  region text DEFAULT '',
  spend numeric DEFAULT 0,
  reach bigint DEFAULT 0,
  impressions bigint DEFAULT 0,
  results integer DEFAULT 0,
  cost_per_result numeric,
  conversions integer DEFAULT 0,
  cost_per_conversion numeric,
  extracted_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.sm_meta_adsets_breakdowns (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  account_id text NOT NULL,
  campaign_id text NOT NULL,
  adset_id text NOT NULL,
  date_start date NOT NULL,
  date_end date NOT NULL,
  age text DEFAULT '',
  gender text DEFAULT '',
  publisher_platform text DEFAULT '',
  platform_position text DEFAULT '',
  region text DEFAULT '',
  spend numeric DEFAULT 0,
  reach bigint DEFAULT 0,
  impressions bigint DEFAULT 0,
  results integer DEFAULT 0,
  cost_per_result numeric,
  conversions integer DEFAULT 0,
  cost_per_conversion numeric,
  extracted_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.sm_meta_ads_breakdowns (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  account_id text NOT NULL,
  campaign_id text NOT NULL,
  adset_id text NOT NULL,
  ad_id text NOT NULL,
  date_start date NOT NULL,
  date_end date NOT NULL,
  age text DEFAULT '',
  gender text DEFAULT '',
  publisher_platform text DEFAULT '',
  platform_position text DEFAULT '',
  region text DEFAULT '',
  spend numeric DEFAULT 0,
  reach bigint DEFAULT 0,
  impressions bigint DEFAULT 0,
  results integer DEFAULT 0,
  cost_per_result numeric,
  conversions integer DEFAULT 0,
  cost_per_conversion numeric,
  extracted_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.sm_meta_campaigns_regions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id text,
  campaign_id text NOT NULL,
  campaign_name text,
  region text,
  date_start date,
  date_end date,
  spend numeric DEFAULT 0,
  reach integer DEFAULT 0,
  impressions integer DEFAULT 0,
  leads integer DEFAULT 0,
  messages integer DEFAULT 0,
  page_views integer DEFAULT 0,
  results integer DEFAULT 0,
  cost_per_result numeric DEFAULT 0,
  extracted_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.sm_meta_sync_control (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  account_id text NOT NULL,
  last_sync_date date NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- 5. Criar tabelas RD Station
CREATE TABLE IF NOT EXISTS public.sm_rdstation_metrics (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  period text NOT NULL,
  period_start date,
  period_end date,
  segmentation_id integer,
  segmentation_name text,
  total_leads integer,
  source text DEFAULT 'rdstation',
  created_at timestamptz DEFAULT now(),
  synced_at timestamptz
);

-- 6. Criar tabelas Eduzz
CREATE TABLE IF NOT EXISTS public.sm_eduzz_invoices (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  invoice_id text,
  status text NOT NULL,
  buyer_name text,
  buyer_email text,
  buyer_phone text,
  product_id text,
  product_name text,
  product_type text,
  valor_item numeric,
  ganho numeric,
  parcelas integer DEFAULT 1,
  created_at timestamptz,
  paid_at timestamptz,
  is_abandonment boolean DEFAULT false,
  utm_campaign text,
  event_type text,
  raw_data jsonb,
  received_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.sm_eduzz_metrics_by_product (
  product_id text,
  product_name text,
  product_type text,
  total_tentativas bigint,
  total_vendas bigint,
  receita_bruta numeric,
  receita_liquida numeric,
  taxa_conversao numeric
);

CREATE TABLE IF NOT EXISTS public.sm_eduzz_metrics_daily (
  date date,
  tentativas bigint,
  vendas bigint,
  abandonos bigint,
  valor_total_bruto numeric,
  valor_total_liquido numeric,
  taxa_conversao numeric
);

-- 7. Criar tabela Dashboard Summary
CREATE TABLE IF NOT EXISTS public.sm_dashboard_summary (
  leads_rd_station integer,
  rd_period text,
  funil_leads integer,
  funil_oportunidades bigint,
  funil_vendas bigint,
  eduzz_tentativas bigint,
  eduzz_vendas bigint,
  eduzz_receita_bruta numeric,
  eduzz_receita_liquida numeric,
  taxa_lead_to_checkout numeric,
  taxa_checkout_to_sale numeric,
  taxa_lead_to_sale numeric,
  last_updated timestamptz
);

-- 8. Criar tabelas CRM
CREATE TABLE IF NOT EXISTS public.sm_crm_deals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id uuid NOT NULL DEFAULT '1e9bc1d6-a6d9-470c-9a90-6afc96ba9ada'::uuid REFERENCES public.tryvia_analytics_clients(id),
  deal_id bigint NOT NULL,
  deal_name text,
  pipeline_id bigint,
  pipeline_name text,
  stage_id bigint,
  stage_name text,
  price numeric DEFAULT 0,
  date_created date,
  date_closed date,
  responsible_id bigint,
  lost_reason_id bigint,
  lost_reason_name text,
  source text,
  origin text,
  status text,
  contacts_created_same_day integer DEFAULT 0,
  extracted_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.sm_crm_metrics (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id uuid NOT NULL DEFAULT '1e9bc1d6-a6d9-470c-9a90-6afc96ba9ada'::uuid REFERENCES public.tryvia_analytics_clients(id),
  date date NOT NULL,
  source text NOT NULL,
  leads integer DEFAULT 0,
  opportunities integer DEFAULT 0,
  sales integer DEFAULT 0,
  revenue numeric DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

-- 9. Habilitar RLS em todas as tabelas
ALTER TABLE public.sm_google_ad_metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sm_google_keywords ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sm_meta_campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sm_meta_adsets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sm_meta_ads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sm_meta_campaigns_breakdowns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sm_meta_adsets_breakdowns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sm_meta_ads_breakdowns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sm_meta_campaigns_regions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sm_meta_sync_control ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sm_rdstation_metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sm_eduzz_invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sm_eduzz_metrics_by_product ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sm_eduzz_metrics_daily ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sm_dashboard_summary ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sm_crm_deals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sm_crm_metrics ENABLE ROW LEVEL SECURITY;

-- 10. Criar políticas RLS para todas as tabelas
CREATE POLICY "SM data access" ON public.sm_google_ad_metrics FOR SELECT USING (has_sm_client_access(auth.uid()));
CREATE POLICY "SM data access" ON public.sm_google_keywords FOR SELECT USING (has_sm_client_access(auth.uid()));
CREATE POLICY "SM data access" ON public.sm_meta_campaigns FOR SELECT USING (has_sm_client_access(auth.uid()));
CREATE POLICY "SM data access" ON public.sm_meta_adsets FOR SELECT USING (has_sm_client_access(auth.uid()));
CREATE POLICY "SM data access" ON public.sm_meta_ads FOR SELECT USING (has_sm_client_access(auth.uid()));
CREATE POLICY "SM data access" ON public.sm_meta_campaigns_breakdowns FOR SELECT USING (has_sm_client_access(auth.uid()));
CREATE POLICY "SM data access" ON public.sm_meta_adsets_breakdowns FOR SELECT USING (has_sm_client_access(auth.uid()));
CREATE POLICY "SM data access" ON public.sm_meta_ads_breakdowns FOR SELECT USING (has_sm_client_access(auth.uid()));
CREATE POLICY "SM data access" ON public.sm_meta_campaigns_regions FOR SELECT USING (has_sm_client_access(auth.uid()));
CREATE POLICY "SM data access" ON public.sm_meta_sync_control FOR SELECT USING (has_sm_client_access(auth.uid()));
CREATE POLICY "SM data access" ON public.sm_rdstation_metrics FOR SELECT USING (has_sm_client_access(auth.uid()));
CREATE POLICY "SM data access" ON public.sm_eduzz_invoices FOR SELECT USING (has_sm_client_access(auth.uid()));
CREATE POLICY "SM data access" ON public.sm_eduzz_metrics_by_product FOR SELECT USING (has_sm_client_access(auth.uid()));
CREATE POLICY "SM data access" ON public.sm_eduzz_metrics_daily FOR SELECT USING (has_sm_client_access(auth.uid()));
CREATE POLICY "SM data access" ON public.sm_dashboard_summary FOR SELECT USING (has_sm_client_access(auth.uid()));
CREATE POLICY "SM data access" ON public.sm_crm_deals FOR SELECT USING (has_sm_client_access(auth.uid()));
CREATE POLICY "SM data access" ON public.sm_crm_metrics FOR SELECT USING (has_sm_client_access(auth.uid()));

-- 11. Criar índices para performance
CREATE INDEX IF NOT EXISTS idx_sm_google_ad_metrics_date ON public.sm_google_ad_metrics(date);
CREATE INDEX IF NOT EXISTS idx_sm_google_ad_metrics_client ON public.sm_google_ad_metrics(client_id);
CREATE INDEX IF NOT EXISTS idx_sm_google_keywords_date ON public.sm_google_keywords(date);
CREATE INDEX IF NOT EXISTS idx_sm_meta_campaigns_dates ON public.sm_meta_campaigns(date_start, date_end);
CREATE INDEX IF NOT EXISTS idx_sm_meta_adsets_dates ON public.sm_meta_adsets(date_start, date_end);
CREATE INDEX IF NOT EXISTS idx_sm_meta_ads_dates ON public.sm_meta_ads(date_start, date_end);
CREATE INDEX IF NOT EXISTS idx_sm_crm_deals_client ON public.sm_crm_deals(client_id);
CREATE INDEX IF NOT EXISTS idx_sm_crm_deals_date ON public.sm_crm_deals(date_created);
CREATE INDEX IF NOT EXISTS idx_sm_crm_metrics_date ON public.sm_crm_metrics(date);